"""Shared constants for final packaging."""

DEFAULT_NOISE_NAME = "default"
NOISE_CUT_DURATION_SECONDS = 60
NOISE_CUTS_PER_SEGMENT = 2
NOISE_STATE_FILE_NAME = "state.json"

PLACEHOLDER_DIR_NAME = "placeholder"
PLACEHOLDER_OUTPUT_STEM = "placeholder"
PLACEHOLDER_STATE_FILE_NAME = "state.json"

REMIX_SEGMENT_SECONDS = 8 * 60
REMIX_MIN_SEGMENT_SECONDS = 60
