"""Shared constants for final packaging."""

DEFAULT_NOISE_NAME = "default"
NOISE_CUT_DURATION_SECONDS = 60
NOISE_STATE_FILE_NAME = "state.json"

PLACEHOLDER_DIR_NAME = "placeholder"
PLACEHOLDER_OUTPUT_STEM = "judge"
PLACEHOLDER_STATE_FILE_NAME = "state.json"

REMIX_TARGET_SEGMENT_SECONDS = 15 * 60
REMIX_MIN_SEGMENT_COUNT = 2
REMIX_MIN_SEGMENT_SECONDS = 60
