"""Shared constants for final packaging."""

NOISE_CHUNK_DURATION_SECONDS = 60
NOISE_CHUNKS_PER_SEGMENT = 2
NOISE_SOURCE_SUFFIX = ".webm"
NOISE_STATE_FILE_NAME = "state.json"

REMIX_SEGMENT_SECONDS = 8 * 60
REMIX_MIN_SEGMENT_SECONDS = 60
